### ISSUE TITLE
Deploy TokenDistroV2 to Optimism & Gnosis Chain

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/givpower#42]
We need to deploy a new version of the token distro to both of these chains in the title, this will involved deploying the contracts then calling the upgrade to the proxyadmin to the proxy from the multisig on each chain.

## Tasks

- [x] Deploy Gnosis Chain tokenDistroV2
- [x] Deploy Optimism tokenDistroV2
- [x] upgrade GC tokendistro proxy
- [x] upgrade OP tokendistro proxy

**Comment by divine-comedian** [comment]
@aminlatifi 

Testing this out on OP Sepolia - 

I assigned `0x62Bb362d63f14449398B79EBC46574F859A6045D` as a distributor and gave it 1000 tokens to distribute 

I allocated 10 tokens to `0x826976d7C600d45FB8287CA1d7c76FC8eb732030` then used transferAllocation to move it to  `0x81443887E6Aef75de940B7244783f896B1c034Ca` 

it shows up correctly on the https://staging.giveth.io/givstream UI as 4.97 tokens claimable - I did not claim those tokens.

I allocated 10 tokens to `0x26135A4FC941828b063165c5C9311eF3bfeea4e5` then used transferAllocation to move it to  `0x81443887E6Aef75de940B7244783f896B1c034Ca` 

the UI does not update - I should have ~9.9 tokens to claim now on the page

checking on the contract it says I have a balance of 20 tokens and claimableNow is ~9.9 tokens

I click claim from the UI and I claim 9.9 GIV tokens from the tokenDistro successfully. 
https://sepolia-optimism.etherscan.io/tx/0xd75983ce63016d3975fef9d727bd4ceea1eefc504df281d967f030a0077120e6#eventlog

This looks like an issue with the subgraph since the amounts on the contract appear to be correct.

**Comment by aminlatifi** [comment]
> 0x81443887E6Aef75de940B7244783f896B1c034Ca

Subgraph is correct, the frontend is merged as well and must be fine. @divine-comedian would you please check?

<img width="982" alt="image" src="https://github.com/Giveth/giveconomy-foundry/assets/5684607/63c7a831-6bbe-4d35-824a-481c8fabff60">

**Comment by divine-comedian** [comment]
Tested again with both transferAllocation and changeAddress functions and transferring allocations successfully added to each other instead of overwriting.

@aminlatifi what else needs to be done for deploying to production?

**Comment by aminlatifi** [comment]
> Tested again with both transferAllocation and changeAddress functions and transferring allocations successfully added to each other instead of overwriting.
> 
> @aminlatifi what else needs to be done for deploying to production?

Good, in my view we can go.

**Comment by divine-comedian** [comment]
Noting here: 

- [ ] Update documentation with new contract implementation addresses
